apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-nginx-deployment
spec:
  replicas: 2 # Start with 2 replicas
  selector:
    matchLabels:
      app: custom-nginx
  template:
    metadata:
      labels:
        app: custom-nginx
    spec:
      containers:
      - name: custom-nginx
        image: ayushiii0308/custom-nginx:latest # Use your custom image
        ports:
        - containerPort: 80
